# Copyright (c) 2025 Mercedes-Benz AG
# Frank Sprünken <accenture.spruenken@extaccount.com>
#
# Version History:
# 1.0.0 - 2025-11-24 - Initial release (F. Sprünken)
#
name: Delete Partner Directory Entry from BTP
description: Delete Partner Directory Entry from BTP

inputs:
  bearer-token:
    description: "BEARER Token to access Partner Directory"
    required: true
  btp-api-url:
    description: "URL on BTP to access APIs"
    required: true
  partner-id:
    description: "Partner ID to delete"
    required: true

runs:
  using: "composite"
  steps:
    - id: delete-pid
      shell: bash
      env:
        BEARER_TOKEN: ${{ inputs.bearer-token }}
        BTP_API_URL: ${{ inputs.btp-api-url }}
        PARTNERID: ${{ inputs.partner-id }}
      run: |
        echo "DELETE Partner ID $PARTNERID from $BTP_API_URL/api/v1/Partners('$PARTNERID')"

        curl_response=$(curl -s -w "\n%{http_code}" -X DELETE "$BTP_API_URL/api/v1/Partners('$PARTNERID')" \
          -H "Authorization: $BEARER_TOKEN")

        HTTP_STATUS=$(echo "$curl_response" | tail -n1)
        BODY=$(echo "$curl_response" | sed '$d')

        # Status must be 204
        if [ "$HTTP_STATUS" != "204" ]; then
          echo "Error: HTTP status $HTTP_STATUS received while deleting $PARTNERID"
          echo "Response body: $BODY"
          exit 1
        fi
        echo "HTTP status $HTTP_STATUS received. Deletion of $PARTNERID successfully!"