# Copyright (c) 2025 Mercedes-Benz AG
# Oliver Weng <sap.weng@extaccount.com>
#
# Version History:
# 1.0.0 - 2025-11-24 - Initial release (O. Weng)
#
name: Pass JSON with IDs to be added for deployment
description: Pass JSON with IDs to be added to .github/actions/perform-deployment/data/$STAGE/DeployTask.${PACKAGEID}

inputs:
  PACKAGEID:
    required: true
  PACKAGENAME:
    required: true    
  FILE:
    required: true
  STAGE:
    required: true

runs:
  using: "composite"
  steps:
    - id: add-ids-for-deployment
      shell: bash
      env:
        PACKAGEID: ${{ inputs.PACKAGEID }}
        PACKAGENAME: ${{ inputs.PACKAGENAME }}
        FILE: ${{ inputs.FILE }}
        STAGE: ${{ inputs.STAGE }}
      run: |
        # Check if file was passed
        if [[ -f "$FILE" ]]; then
          echo "✅ File with IDs found: $FILE"
        else
          echo "❌ File with IDs not found: $FILE"
          exit 1
        fi

        # Extract the filename (basename)
        filename=$(basename "$FILE")
        first_part=${filename%%.*}
        # Remove 'DesigntimeArtifacts' from the first part
        ArtifactType=${first_part//DesigntimeArtifacts/}
        echo "Detected ArtifactType = $ArtifactType"

        # Set FileName for Output
        DEPLOY_RESULT=".github/actions/perform-deployment/data/$STAGE/DeployTask.${PACKAGEID}"
       
        # Extract all IDs from FILE
        ids=$(jq -r '.d.results[] | .Id' "$FILE")

        echo "Hoer"

        # Exit early if no IDs were found
        if [[ -z "$ids" ]]; then
          echo "No IDs found for type '$ArtifactType'. Nothing to Deploy."
          exit 0
        fi

        echo "Oder joer"

        # Add each ID for deployment
        for id in $ids; do
          echo "✅ Add $id to deployment"

          # Get ArtifactName
          ArtifactName=$(jq -r --arg id "$id" '.d.results[] | select(.Id == $id) | .Name' "$FILE")
          
          # Add ID to DEPLOY_RESULT
          # Check whether file exists. If not create header and remember 
          if [ ! -f "$DEPLOY_RESULT" ]; then
            echo "❌ File $DEPLOY_RESULT does not exist. Creating it..."
            mkdir -p .github/actions/perform-deployment/data/$STAGE
              
            jq -n \
            --arg id "$id" \
            --arg name "$ArtifactName" \
            --arg type "$ArtifactType" \
            --arg action "Deploy" \
            --arg packageid "$PACKAGEID" \
            --arg packagename "$PACKAGENAME" \
            '{d: {deploytasks: [{id: $id, name: $name, type: $type, action: $action}], packageid: $packageid, packagename: $packagename}}' > "$DEPLOY_RESULT"

          else
            # Add new entry
            echo "✅ $DEPLOY_RESULT available -> Insert entry"

            jq --arg id "$id" --arg name "$ArtifactName" --arg type "$ArtifactType" \
            '.d.deploytasks += (
              if (.d.deploytasks // [] | any(.id == $id and .name == $name and .type == $type and .action == "Deploy")) 
                then [] 
              else [{"id": $id, "name": $name, "type": $type, "action": "Deploy"}] 
              end
            )' "$DEPLOY_RESULT" > tmp.json && mv tmp.json "$DEPLOY_RESULT"


          fi
        done
        
        cat $DEPLOY_RESULT
        
