# Copyright (c) 2025 Mercedes-Benz AG
# Oliver Weng <sap.weng@extaccount.com>
#
# Version History:
# 1.0.0 - 2025-11-24 - Initial release (O. Weng)
#
name: Get CPI Package Name
description: Get Package Name from CPI Designtime

inputs:
  bearer-token:
    description: "BEARER Token to access Integration Suite Artifacts"
    required: true
    type: string
  btp-api-url:
    description: "URL on BTP to access APIs"
    required: true
    type: string
  package-id:
    description: "Package ID"
    required: true
    type: string

outputs:
  name:
    description: 'Name of Package'
    value: ${{ steps.get-package-name.outputs.name }}

runs:
  using: "composite"
  steps:
    - id: get-package-name
      shell: bash
      env:
        BEARER_TOKEN: ${{ inputs.bearer-token }}
        BTP_API_URL: ${{ inputs.btp-api-url }}
        PACKAGEID: ${{ inputs.package-id }}
      run: |
        echo "Download PackageID $PACKAGEID Details from $BTP_API_URL/api/v1/IntegrationPackages('$PACKAGEID')?\$format=json"
        echo "Get Package Name for $PACKAGEID"

        curl_response=$(curl -s -w "\n%{http_code}" -X GET "$BTP_API_URL/api/v1/IntegrationPackages('$PACKAGEID')?\$format=json" \
          -H "Authorization: $BEARER_TOKEN")

        HTTP_STATUS=$(echo "$curl_response" | tail -n1)
        BODY=$(echo "$curl_response" | sed '$d')

        if [ "$HTTP_STATUS" != "200" ]; then
          echo "Error: HTTP status $HTTP_STATUS received while requesting package metadata."
          echo "Response body: $BODY"
          exit 1
        fi

        echo "$BODY"

        # Extract PackageName using xmllint ignoring namespaces
        PACKAGENAME=$(echo "$BODY" | jq -r '.d.Name')

        # Exit if PACKAGENAME is null or empty
        if [[ -z "$PACKAGENAME" ]]; then
          echo "PACKAGENAME is null or empty. Exiting."
        exit 1
        fi

        echo "Extracted PackageName: $PACKAGENAME"
        
        PACKAGENAME="${PACKAGENAME// /_}"
        echo "Modified PackageName (no spaces): $PACKAGENAME"
        
        echo "name=$PACKAGENAME" >> "$GITHUB_OUTPUT"
