# Copyright (c) 2025 Mercedes-Benz AG
# Oliver Weng <sap.weng@extaccount.com>
#
# Version History:
# 1.0.0 - 2025-11-24 - Initial release (O. Weng)
#
name: Get Object IDs of Package
description: Get Object IDs of Package

inputs:
  bearer-token:
    description: "BEARER Token to access Integration Suite Artifacts"
    required: true
    type: string
  btp-api-url:
    description: "URL on BTP to access APIs"
    required: true
    type: string
  package-id:
    description: "Package ID"
    required: true
    type: string
  object-type:
    required: true
    description: "Artifact Object Type"
    options:
          - Integration
          - ValueMapping
          - MessageMapping
          - ScriptCollection

outputs:
  file:
    description: 'File with List of IDs'
    value: ${{ steps.get-object-ids.outputs.file }}

runs:
  using: "composite"
  steps:
    - id: get-object-ids
      shell: bash
      env:
        BEARER_TOKEN: ${{ inputs.bearer-token }}
        BTP_API_URL: ${{ inputs.btp-api-url }}
        PACKAGEID: ${{ inputs.package-id }}
        OBJECTTYPE: ${{ inputs.object-type }}
      run: |
        echo "Get ${OBJECTTYPE} IDs from $PACKAGEID from $BTP_API_URL/api/v1/IntegrationPackages('$PACKAGEID')/${OBJECTTYPE}DesigntimeArtifacts?\$format=json"

        curl_response=$(curl -s -w "\n%{http_code}" -X GET "$BTP_API_URL/api/v1/IntegrationPackages('$PACKAGEID')/${OBJECTTYPE}DesigntimeArtifacts?\$format=json" \
          -H "Authorization: $BEARER_TOKEN")

        HTTP_STATUS=$(echo "$curl_response" | tail -n1)
        BODY=$(echo "$curl_response" | sed '$d')

         # Status can be 200 Found or 404 Not Found (Package not Available)
        if [ "$HTTP_STATUS" != "200" ] && [ "$HTTP_STATUS" != "404" ]; then
          echo "Error: HTTP status $HTTP_STATUS received while requesting ${OBJECTTYPE} IDs"
          echo "Response body: $BODY"
          exit 1
        fi

        OUTPUTFILE=${{ runner.temp }}/${OBJECTTYPE}DesigntimeArtifacts.$PACKAGEID

        if [ "$HTTP_STATUS" = "200" ]; then
          echo "Writing ${OBJECTTYPE}DesigntimeArtifacts of Package $PACKAGEID to file $OUTPUTFILE"
          echo "$BODY" > "$OUTPUTFILE"
        else
          echo "Package not found. Writing empty file $OUTPUTFILE"
          echo '{' > "$OUTPUTFILE"
          echo '  "d": {' >> "$OUTPUTFILE"
          echo '    "results": []' >> "$OUTPUTFILE"
          echo '  }' >> "$OUTPUTFILE"
          echo '}' >> "$OUTPUTFILE"
        fi     
        
        


        echo "file=${{ runner.temp }}/${OBJECTTYPE}DesigntimeArtifacts.$PACKAGEID" >> "$GITHUB_OUTPUT"
