# Copyright (c) 2025 Mercedes-Benz AG
# Frank Sprünken <accenture.spruenken@extaccount.com>
#
# Version History:
# 1.0.0 - 2025-11-24 - Initial release (F. Spruenken)
#

name: (Dev) Update Externalized Parameters for IFlow on DEV or TST

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Environment"
        required: true
        type: choice
        options:
          - DEV
          - TST
      iflow-id:
        description: "IFlow ID"
        required: true
        type: string
      iflow-deploy:
        description: "Deploy Integration Flow?"
        required: true
        type: choice
        options:
          - "false"
          - "true"

permissions:
  contents: write

jobs:
  authorize:
    name: Authorization Check
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    steps:     
      - name: Check team authorization
        uses: SAP/cicd-actions-for-sap-integration-suite/.github/actions/check-team-authorization@v1
        with:
          team-slug: ${{ vars.BTP_DEV_TEAM_SLUG }}
          github-token: ${{ secrets.GIT_ORG_TOKEN }}
          
  read-env-vars:
    needs: authorize
    name: Read Environment Variables and Secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    outputs:
      btp-api-user: ${{ steps.export.outputs.btp-api-user }}
      btp-tec-user: ${{ steps.export.outputs.btp-tec-user }}
      btp-token-url: ${{ steps.export.outputs.btp-token-url }}
      btp-api-url: ${{ steps.export.outputs.btp-api-url }}
    steps:
      - name: Export secrets and vars
        id: export
        run: |
          echo "::add-mask::${{ secrets.BTP_API_PASSWORD }}"
          echo "::add-mask::${{ secrets.BTP_TEC_PASSWORD }}"
          echo "::add-mask::${{ secrets.GIT_CICD_TOKEN }}"
        
          echo "btp-api-user=${{ vars.BTP_API_USER }}" >> $GITHUB_OUTPUT
          echo "btp-tec-user=${{ vars.BTP_TEC_USER }}" >> $GITHUB_OUTPUT
          echo "btp-token-url=${{ vars.BTP_TOKEN_URL }}" >> $GITHUB_OUTPUT
          echo "btp-api-url=${{ vars.BTP_API_URL }}" >> $GITHUB_OUTPUT

  update-externalized-iflow-parameters:
    needs: read-env-vars
    uses: SAP/cicd-actions-for-sap-integration-suite/.github/workflows/update-externalized-iflow-parameters.yml@v1
    with:
       workflow-ref: v1
       target-env: ${{ inputs.target-env }}
       iflow-id: ${{ inputs.iflow-id }}
       source-ref: development
       iflow-deploy: ${{ inputs.iflow-deploy }}
       btp-api-user: ${{ needs.read-env-vars.outputs.btp-api-user }}
       btp-tec-user: ${{ needs.read-env-vars.outputs.btp-tec-user }}
       btp-token-url: ${{ needs.read-env-vars.outputs.btp-token-url }}
       btp-api-url: ${{ needs.read-env-vars.outputs.btp-api-url }}
       git-cicd-orgrepo: ${{ vars.GIT_CICD_ORGREPO }}       
    secrets:
       BTP_TEC_PASSWORD: ${{ secrets.BTP_TEC_PASSWORD }}
       BTP_API_PASSWORD: ${{ secrets.BTP_API_PASSWORD }}
       GIT_CICD_TOKEN: ${{ secrets.GIT_CICD_TOKEN }}
