# Copyright (c) 2025 Mercedes-Benz AG
# Oliver Weng <sap.weng@extaccount.com>
#
# Version History:
# 1.0.0 - 2025-11-24 - Initial release (O. Weng)
#

name: (Admin) BTP Deploy/Delete Manager

on:
  workflow_dispatch:
    inputs:
      upload-ids:
        description: "Comma-separated list of IDs to upload"
        required: false
        type: string
      delete-ids:
        description: "Comma-separated list of IDs to delete"
        required: false
        type: string		
      mode:
        description: "Mode IntegrationPackages/PartnerDirectory"
        required: true
        type: choice
        options:
          - IntegrationPackages
          - PartnerDirectory
      source-ref:
        description: "GIT Source Reference"
        required: true
        type: string   
      target-env:
        description: "Target BTP Environment"
        required: false
        type: choice
        options:
          - PRD
          - TST
          - DEV

permissions:
  contents: write

jobs:
  authorize:
    name: Authorization Check
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    steps:     
      - name: Check team authorization
        uses: SAP/cicd-actions-for-sap-integration-suite/.github/actions/check-team-authorization@v1
        with:
          team-slug: ${{ vars.BTP_ADMIN_TEAM_SLUG }}
          github-token: ${{ secrets.GIT_ORG_TOKEN }}

  read-env-vars:
    needs: authorize
    name: Read Vars & Secrets ${{ github.event.inputs.target-env }}
    environment: ${{ github.event.inputs.target-env }}
    runs-on: ubuntu-latest
    outputs:
      btp-api-user: ${{ steps.export.outputs.btp-api-user }}
      btp-tec-user: ${{ steps.export.outputs.btp-tec-user }}
      btp-token-url: ${{ steps.export.outputs.btp-token-url }}
      btp-api-url: ${{ steps.export.outputs.btp-api-url }}
      git-api-url: ${{ steps.export.outputs.git-api-url }}
      BTP_API_PASSWORD: ${{ steps.export.outputs.BTP_API_PASSWORD }}
      BTP_TEC_PASSWORD: ${{ steps.export.outputs.BTP_TEC_PASSWORD }}
      GIT_CICD_TOKEN: ${{ steps.export.outputs.GIT_CICD_TOKEN }}
    steps:
      - name: Export secrets and vars
        id: export
        run: |
          echo "::add-mask::${{ secrets.BTP_API_PASSWORD }}"
          echo "::add-mask::${{ secrets.BTP_TEC_PASSWORD }}"
          echo "::add-mask::${{ secrets.GIT_CICD_TOKEN }}"
          echo "btp-api-user=${{ vars.BTP_API_USER }}" >> $GITHUB_OUTPUT
          echo "btp-tec-user=${{ vars.BTP_TEC_USER }}" >> $GITHUB_OUTPUT
          echo "btp-token-url=${{ vars.BTP_TOKEN_URL }}" >> $GITHUB_OUTPUT
          echo "btp-api-url=${{ vars.BTP_API_URL }}" >> $GITHUB_OUTPUT
      
  btp-process-ids:
    needs: [read-env-vars]
    name: Process ${{ github.event.inputs.mode }}
    uses: SAP/cicd-actions-for-sap-integration-suite/.github/workflows/delete-upload.yml@v1
    with:
      workflow-ref: v1		
      target-env: ${{ github.event.inputs.target-env }}
      source-ref: ${{ github.event.inputs.source-ref }}
      integrationpackages-delete-ids: ${{ github.event.inputs.mode == 'IntegrationPackages' && github.event.inputs.delete-ids || '' }}
      integrationpackages-upload-ids: ${{ github.event.inputs.mode == 'IntegrationPackages' && github.event.inputs.upload-ids || '' }}
      partnerdirectory-delete-ids: ${{ github.event.inputs.mode == 'PartnerDirectory' && github.event.inputs.delete-ids || '' }}
      partnerdirectory-upload-ids: ${{ github.event.inputs.mode == 'PartnerDirectory' && github.event.inputs.upload-ids || '' }}
      btp-api-user: ${{ needs.read-env-vars.outputs.btp-api-user }}
      btp-tec-user: ${{ needs.read-env-vars.outputs.btp-tec-user }}
      btp-token-url: ${{ needs.read-env-vars.outputs.btp-token-url }}
      btp-api-url: ${{ needs.read-env-vars.outputs.btp-api-url }}
      git-cicd-orgrepo: ${{ vars.GIT_CICD_ORGREPO }}      
    secrets:
      BTP_TEC_PASSWORD: ${{ secrets.BTP_TEC_PASSWORD }}
      BTP_API_PASSWORD: ${{ secrets.BTP_API_PASSWORD }}
      GIT_CICD_TOKEN: ${{ secrets.GIT_CICD_TOKEN }}